In [1]:
import pandas as pd
from IPython.display import display
from jqdatasdk import *

In [ ]:
auth()

auth success

In [3]:
get_query_count()

{'total': 1000000, 'spare': 1000000}

In [6]:
df_2025 =get_price('159920.XSHE', start_date= '2025-01-01 09:30:00',end_date='2025-12-14 15:00:00',\
              fq='pre', frequency='minute',\
              fields=['open','close','low','high','volume'],round=False) 
display(df_2025.head())

                      open  close    low   high      volume
2025-01-02 09:31:00  1.236  1.234  1.234  1.236  18560200.0
2025-01-02 09:32:00  1.233  1.234  1.233  1.234   7802200.0
2025-01-02 09:33:00  1.234  1.233  1.233  1.235   3979000.0
2025-01-02 09:34:00  1.233  1.229  1.229  1.234  15380800.0
2025-01-02 09:35:00  1.230  1.231  1.229  1.231   2429800.0

In [ ]:
# 将index 转化为列date
df_2025.reset_index(inplace=True, names='date')
display(df_2025.head())

                 date   open  close    low   high      volume
0 2025-01-02 09:31:00  1.236  1.234  1.234  1.236  18560200.0
1 2025-01-02 09:32:00  1.233  1.234  1.233  1.234   7802200.0
2 2025-01-02 09:33:00  1.234  1.233  1.233  1.235   3979000.0
3 2025-01-02 09:34:00  1.233  1.229  1.229  1.234  15380800.0
4 2025-01-02 09:35:00  1.230  1.231  1.229  1.231   2429800.0

In [17]:
df_2025.to_csv('raw_data/159920_XSHE_2025.csv',index=True, encoding="utf-8-sig")